name: Test

on: [push, pull_request, workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
      name: List the state of node modules
      continue-on-error: true
      run: npm list

    - name: Install virtual framebuffer
      run: sudo apt-get install xvfb

    - name: Install dependencies
      run: npm install

    - name: Test
      run: xvfb-run --auto-servernum npm run test

    - name: Upload coverage to Codecov.io
      uses: codecov/codecov-action@v2
